Add icon guidelines
opencast/appkit pull request #2
Opened 2023-10-04 11:03 UTC by LukasKalbertodt

There was some discussion about this in https://github.com/opencast/opencast-editor/pull/1079 and elsewhere. This PR adds the guidelines that (to my understanding) we agreed on. Just to have those somewhere for reference.

Note: I, too, dislike that we have the "Hero" exception at all. Just saying "Lucide!" as the full guideline would be nicer. But the two mentioned icons (`search` and `translate`) are already used in Tobira, Studio and Editor for a long time already and I honestly think they look much better than the Lucide alternatives. We also talked about this internally and everyone agreed on that.

CC @lkiesow @Arnei

2023-11-08 13:45 UTC, lkiesow requested changes
You know we disagree on this and you still describe this pull request as if everyone agrees and really likes this.

> But the two mentioned icons (search and translate) are already used in Tobira, Studio and Editor for a long time already

What you wanted to say is that we disagreed, you put them in and are now arguing that they are in, and it should be the default. That is not a nice argument and somewhat concerning.

> We also talked about this internally and everyone agreed on that.

We talked about that. That's correct. I did not remember to agree? I actually remember to disagree.

---

But ignoring the pull request description, I would make this much simpler and basically just say:

- „Use Lucide, but be pragmatic.“

Because you are trying to handle one special case in the rules. This means that once the next special cases pops up, you would basically need to rewrite this. That means, just pointing out to be pragmatic and do something else if there is a good reason should be fine.

2023-11-08 13:45 UTC, lkiesow commented on README.md
> +  - Hero's `translate` is much better than Lucides `languages` and more on point than `globe`.
This is highly subjective and shouldn't go into our docs.

2023-11-08 13:45 UTC, lkiesow commented on README.md
> +  Currently, there are two important exceptions in which you should use the Hero icons:
```suggestion
- Be pragmatic and use something else if there is a good reasone for that.
```

2023-11-08 14:13 UTC, LukasKalbertodt commented
I feel like your tone is unnecessarily hostile and that doesn't help anyone. I guess you have the feeling I just wanted to brush your concerns under the rug (which would suck, I agree), but give others the benefit of the doubt: I actually truthfully thought our disagreement on this was fully or almost fully resolved in the linked editor PR.

I remember the main disagreement being about me voting to continue to use Feather even though it does not accept PRs and does not have a lot of icons. Then we found Lucide, which solves both of these problems. In [this comment](https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1684241992), you say "Lucide is a good compromise". You also +1'ed [this comment](https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1688165508) with my suggestion to "ignore Feather and just use Lucide".

And this is almost exactly what this PR here is doing: saying "use Lucide". The only difference is that I single out two specific icons from Hero. So I'm really very surprised that your review sounds like you are 100% opposed to this.


> > But the two mentioned icons (search and translate) are already used in Tobira, Studio and Editor for a long time already
> 
> What you wanted to say is that we disagreed, you put them in and are now arguing that they are in, and it should be the default. That is not a nice argument and somewhat concerning.

We decided on these two icons together with Lisa, with her maybe even suggesting one over the Feather alternative. It's not like I ignored everyone else, just pushed this, and then described it as status quo. 

If you disagree with singling out these two icons and think that the guideline should *just* be "use Lucide", that's fair. That would be something we can discuss.


> > We also talked about this internally and everyone agreed on that.
> 
> We talked about that. That's correct. I did not remember to agree? I actually remember to disagree.

I referred to a more recent ELAN internal discussion after you left ELAN. And even if this was referring to the editor PR discussion (which I think was the last discussion we had), my understanding was, as described above, that we basically agreed.


> But ignoring the pull request description, I would make this much simpler and basically just say:
> 
> * „Use Lucide, but be pragmatic.“
> 
> Because you are trying to handle one special case in the rules. This means that once the next special cases pops up, you would basically need to rewrite this. That means, just pointing out to be pragmatic and do something else if there is a good reason should be fine.

Fair point, we could do that. I was writing this thinking of your valid point that if we give devs too much freedom, we end up with a wild mix of icon libraries. Just mentioning exactly two exceptions felt like a more restrictive way to phrase this guideline. And I thought that was in your interest. But of course my current phrasing still leaves some wiggle room. So either we remove this wiggle room and say "only these two exception exist" or we go your route and just saying "be pragmatic".

2023-11-08 14:15 UTC, LukasKalbertodt commented on README.md
> +    Even if Feather icons are identical to Lucide, always import the Lucide icon for code consistency!
Fair. Feather was used in Studio and Tobira. So I thought this historical note was useful as context for working with these projects. But you are right, it's probably best to just remove this section for brevity.

2024-06-25 15:42 UTC, LukasKalbertodt commented
We just discussed it in dev meeting. Lets merge it then.

2024-06-25 15:42 UTC, merged